import XCTest
@testable import SnoozePay

/// On-disk contract for the per-row currency added in #562.
///
/// `stored_transactions` is the user's money and `TransactionRepository`
/// decodes it as one array, treating ANY decode failure as corruption: it locks
/// writes, backs the blob up and hands the UI an error (#72). So a format change
/// that isn't tolerant does not crash and does not fail loudly — it silently
/// takes every user's history away on upgrade. These tests pin both directions
/// of the format boundary:
///
/// - **forward** — a ledger written before the field decodes whole, as roubles;
/// - **backward** — a ledger written now decodes in a build that has never heard
///   of the field.
///
/// Every decode is `try`, not `try?`: swallowing the error would make these
/// tests pass on exactly the regression they exist to catch.
final class TransactionCurrencyCodableTests: XCTestCase {

    private var testDefaults: UserDefaults!
    private var suiteName: String!

    override func setUp() {
        super.setUp()
        suiteName = "test.txCurrency.\(UUID().uuidString)"
        testDefaults = UserDefaults(suiteName: suiteName)!
    }

    override func tearDown() {
        testDefaults.removePersistentDomain(forName: suiteName)
        testDefaults = nil
        suiteName = nil
        super.tearDown()
    }

    // MARK: - Helpers

    private func decode(_ json: String) throws -> [Transaction] {
        try JSONDecoder().decode([Transaction].self, from: Data(json.utf8))
    }

    private func makeRepo(withBlob json: String) -> TransactionRepository {
        testDefaults.set(Data(json.utf8), forKey: "stored_transactions")
        return TransactionRepository(defaults: testDefaults)
    }

    /// The rows as JSON objects, so assertions are about the persisted *shape*
    /// (which keys exist) and not about `String` formatting of the blob.
    private func encodedRows(_ transactions: [Transaction]) throws -> [[String: Any]] {
        let data = try JSONEncoder().encode(transactions)
        return try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [[String: Any]])
    }

    /// `Transaction` as it was declared before #562 — the same field set, with
    /// `type` as a bare `String` so this mirror stays independent of the app's
    /// enum. Used in both directions: to produce a legacy blob that was NOT
    /// generated by the new encoder, and to stand in for a rolled-back build
    /// reading a blob the new encoder wrote.
    private struct PreCurrencyTransaction: Codable {
        let id: UUID
        let type: String
        let amount: Double
        let alarmID: String?
        let createdAt: Date
        let refundsTransactionID: UUID?

        init(
            id: UUID = UUID(),
            type: String,
            amount: Double,
            alarmID: String? = nil,
            createdAt: Date = Date(timeIntervalSinceReferenceDate: 760_000_000),
            refundsTransactionID: UUID? = nil
        ) {
            self.id = id
            self.type = type
            self.amount = amount
            self.alarmID = alarmID
            self.createdAt = createdAt
            self.refundsTransactionID = refundsTransactionID
        }
    }

    // MARK: - Forward compatibility (ledgers written before #562)

    /// The literal shape found under `stored_transactions` today: no `currency`
    /// key anywhere, optional fields simply absent. Every row must read, and
    /// read as roubles — the store has only ever sold a rouble balance.
    func testDecode_ledgerWrittenBeforeCurrencies_readsWholeAndAsRoubles() throws {
        let chargeID = UUID()
        let decoded = try decode("""
        [
          {"id":"\(UUID().uuidString)","type":"topup","amount":500,"createdAt":760000000},
          {"id":"\(chargeID.uuidString)","type":"charge","amount":50,
           "alarmID":"\(UUID().uuidString)","createdAt":760000100},
          {"id":"\(UUID().uuidString)","type":"refund","amount":50,
           "createdAt":760000200,"refundsTransactionID":"\(chargeID.uuidString)"}
        ]
        """)

        XCTAssertEqual(decoded.count, 3, "A missing currency key is legacy data, not corruption")
        XCTAssertEqual(decoded.map(\.currency), [.legacyDefault, .legacyDefault, .legacyDefault])
        XCTAssertEqual(decoded.map(\.currency), [.rub, .rub, .rub],
                       "The legacy default is the rouble — pinned here so #563 can't move it by accident")
        XCTAssertEqual(decoded.map(\.amount), [500, 50, 50])
        XCTAssertEqual(decoded.last?.refundsTransactionID, chargeID,
                       "The refund link must survive the new field")
    }

    /// Same claim, but the bytes are produced by a model that *is* the old
    /// shape rather than by a hand-typed fixture — so the test keeps holding if
    /// the encoder's conventions (date strategy, omitted optionals) are ever
    /// what changes.
    func testDecode_blobWrittenByThePreCurrencyModel_decodesWhole() throws {
        let legacy = [
            PreCurrencyTransaction(type: "topup", amount: 499),
            PreCurrencyTransaction(type: "charge", amount: 50, alarmID: UUID().uuidString),
            PreCurrencyTransaction(type: "promotion", amount: 100)
        ]
        let data = try JSONEncoder().encode(legacy)

        let decoded = try JSONDecoder().decode([Transaction].self, from: data)

        XCTAssertEqual(decoded.count, 3)
        XCTAssertEqual(decoded.map(\.id), legacy.map(\.id))
        XCTAssertEqual(decoded.map(\.amount), [499, 50, 100])
        XCTAssertTrue(decoded.allSatisfy { $0.currency == .legacyDefault })
    }

    /// The state an install lands in the moment it starts writing: old rows have
    /// no currency, new ones do. Both must read in the same pass — the ledger is
    /// decoded as one array, so "half of it" is not an option.
    func testDecode_mixedLedger_someRowsCarryCurrency_everyRowIsRead() throws {
        let decoded = try decode("""
        [
          {"id":"\(UUID().uuidString)","type":"topup","amount":500,"createdAt":760000000},
          {"id":"\(UUID().uuidString)","type":"charge","amount":50,
           "currency":"RUB","createdAt":760000100},
          {"id":"\(UUID().uuidString)","type":"topup","amount":9,
           "currency":"USD","createdAt":760000200}
        ]
        """)

        XCTAssertEqual(decoded.count, 3)
        XCTAssertEqual(decoded.map(\.currency), [.rub, .rub, Currency(code: "USD")!])
    }

    /// `Currency` canonicalises case on construction (#561). A row written
    /// lowercase — by a storefront value that skipped the wrapper, say — must
    /// read as the same currency rather than lock the ledger.
    func testDecode_lowercaseCurrencyToken_canonicalises() throws {
        let decoded = try decode("""
        [{"id":"\(UUID().uuidString)","type":"topup","amount":10,
          "currency":"usd","createdAt":760000000}]
        """)

        XCTAssertEqual(decoded.first?.currency, Currency(code: "USD")!)
    }

    // MARK: - Round-trip

    /// Every `record()` rewrites the whole array, so the format has to survive
    /// being read and written repeatedly. Legacy in, new out, legacy meaning
    /// preserved.
    func testRoundTrip_legacyLedger_decodeEncodeDecode_isStable() throws {
        let chargeID = UUID()
        let alarmID = UUID().uuidString
        let original = try decode("""
        [
          {"id":"\(chargeID.uuidString)","type":"charge","amount":50,
           "alarmID":"\(alarmID)","createdAt":760000000},
          {"id":"\(UUID().uuidString)","type":"refund","amount":50,
           "createdAt":760000100,"refundsTransactionID":"\(chargeID.uuidString)"}
        ]
        """)

        let reencoded = try JSONEncoder().encode(original)
        let roundTripped = try JSONDecoder().decode([Transaction].self, from: reencoded)

        XCTAssertEqual(roundTripped.map(\.id), original.map(\.id))
        XCTAssertEqual(roundTripped.map(\.type), original.map(\.type))
        XCTAssertEqual(roundTripped.map(\.amount), original.map(\.amount))
        XCTAssertEqual(roundTripped.map(\.currency), original.map(\.currency))
        XCTAssertEqual(roundTripped.map(\.createdAt), original.map(\.createdAt))
        XCTAssertEqual(roundTripped.first?.alarmID, alarmID)
        XCTAssertEqual(roundTripped.last?.refundsTransactionID, chargeID)
    }

    /// A foreign row survives the same cycle unchanged — nothing converts it,
    /// nothing restates it in the wallet's currency (#559).
    func testRoundTrip_foreignRow_keepsItsCurrencyAndAmount() throws {
        let usd = Currency(code: "USD")!
        let original = Transaction(type: .topup, amount: 9.99, currency: usd)

        let data = try JSONEncoder().encode([original])
        let decoded = try JSONDecoder().decode([Transaction].self, from: data)

        XCTAssertEqual(decoded.first?.currency, usd)
        XCTAssertEqual(decoded.first?.amount, 9.99)
    }

    // MARK: - Persisted shape

    func testEncode_writesTheCurrencyOnEveryRow() throws {
        let rows = try encodedRows([
            Transaction(type: .topup, amount: 500),
            Transaction(type: .topup, amount: 9, currency: Currency(code: "USD")!)
        ])

        XCTAssertEqual(rows.map { $0["currency"] as? String }, ["RUB", "USD"],
                       "A row whose currency is implicit is what #562 exists to stop writing")
    }

    /// The rest of the row's shape is unchanged: absent optionals stay absent
    /// (not `null`), so a pre-#562 build sees exactly the JSON it always saw
    /// plus one key it ignores.
    func testEncode_absentOptionals_stayAbsent() throws {
        let rows = try encodedRows([Transaction(type: .topup, amount: 500)])
        let row = try XCTUnwrap(rows.first)

        XCTAssertEqual(Set(row.keys), ["id", "type", "amount", "currency", "createdAt"])
    }

    // MARK: - Rollback

    /// **The downgrade question, answered by decoding rather than by opinion.**
    ///
    /// A rolled-back build decodes with a model that has no `currency` property.
    /// `KeyedDecodingContainer` reads the keys it asks for and ignores the rest,
    /// so the extra key is inert — unlike `.refund` (#358), where the new value
    /// landed in a field the old build *did* read with a strict enum and threw.
    /// Adding a field is therefore reversible; adding a token was not.
    ///
    /// The one loss is denomination: the old build re-encodes without the key,
    /// so a foreign row comes back from a rollback labelled as nothing. That
    /// only becomes reachable once #563 can produce foreign rows; today every
    /// row is roubles and the rollback is lossless.
    func testDowngrade_preCurrencyModelReadsRowsWrittenNow() throws {
        let charge = Transaction(type: .charge, amount: 50, alarmID: UUID().uuidString)
        let foreign = Transaction(type: .topup, amount: 9, currency: Currency(code: "USD")!)
        let data = try JSONEncoder().encode([charge, foreign])

        let asOldBuild = try JSONDecoder().decode([PreCurrencyTransaction].self, from: data)

        XCTAssertEqual(asOldBuild.count, 2, "The unknown key must be ignored, not fatal")
        XCTAssertEqual(asOldBuild.map(\.id), [charge.id, foreign.id])
        XCTAssertEqual(asOldBuild.map(\.type), ["charge", "topup"])
        XCTAssertEqual(asOldBuild.map(\.amount), [50, 9])
        XCTAssertEqual(asOldBuild.first?.alarmID, charge.alarmID)
    }

    // MARK: - Damage

    /// Where the tolerance stops. An unparseable currency is byte damage, and it
    /// is handled like damage to `id` / `amount` / `createdAt`: the #72 gate arms,
    /// the blob is preserved, the user is told. The alternative — reading it as
    /// roubles — would fold an amount of unknown denomination into a rouble
    /// balance, which is silent and unrecoverable rather than loud and
    /// recoverable.
    func testDecode_unparseableCurrency_armsTheCorruptionGateInsteadOfGuessing() throws {
        let repo = makeRepo(withBlob: """
        [
          {"id":"\(UUID().uuidString)","type":"topup","amount":500,
           "currency":"\u{20BD}","createdAt":760000000}
        ]
        """)

        XCTAssertThrowsError(try repo.fetchAllChecked())
        XCTAssertTrue(repo.lastLoadFailed, "Damage must lock the ledger, not be read as roubles")
        XCTAssertNotNil(testDefaults.data(forKey: TransactionRepository.corruptBackupKey),
                        "…and the original bytes must be kept for diagnosis")
    }

    /// The tolerance that already existed (#358) is untouched: a row this build
    /// can't classify by `type` still doesn't take its neighbours down, and it
    /// still carries a currency like any other row.
    func testDecode_unknownTypeTokenBesideCurrencies_stillDoesNotDropTheArray() throws {
        let decoded = try decode("""
        [
          {"id":"\(UUID().uuidString)","type":"topup","amount":500,
           "currency":"RUB","createdAt":760000000},
          {"id":"\(UUID().uuidString)","type":"cashback","amount":25,
           "currency":"RUB","createdAt":760000100},
          {"id":"\(UUID().uuidString)","type":"charge","amount":50,"createdAt":760000200}
        ]
        """)

        XCTAssertEqual(decoded.count, 3, "One unclassifiable row must not cost the other two")
        XCTAssertEqual(decoded.map(\.type), [.topup, .unknown("cashback"), .charge])
        XCTAssertTrue(decoded.allSatisfy { $0.currency == .rub })
    }

    // MARK: - Typed view & rendering

    func testMoney_carriesTheRowsOwnCurrency() {
        let usd = Currency(code: "USD")!

        XCTAssertEqual(Transaction(type: .topup, amount: 9, currency: usd).money,
                       Money(9, currency: usd))
        XCTAssertEqual(Transaction(type: .topup, amount: 9).money, Money.legacy(9))
    }

    /// Rouble rows render exactly as before — the user keeps seeing "50 ₽".
    /// A foreign row must not borrow the rouble glyph: with no conversion
    /// anywhere in the app, "9 ₽" for nine dollars is a wrong number, not a
    /// formatting detail.
    func testFormattedAmount_roubleRowUnchanged_foreignRowIsNotLabelledInRoubles() {
        XCTAssertEqual(Transaction(type: .charge, amount: 50).formattedAmount,
                       "-\(MoneyFormatter.string(50))")

        let foreign = Transaction(type: .topup, amount: 9, currency: Currency(code: "USD")!)
        XCTAssertFalse(foreign.formattedAmount.contains("\u{20BD}"),
                       "A dollar row rendered with ₽ states an amount the ledger never held")
        XCTAssertTrue(foreign.formattedAmount.contains("9"))
    }
}
